# Generated by Django 4.2.1 on 2023-10-25 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('ambulance_type', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('availability_status', models.BooleanField(default=True)),
                ('current_location_latitude', models.FloatField()),
                ('current_location_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('pickup_location', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ambulance_type', models.CharField(choices=[('Basic Ambulance', 'Basic Ambulance'), ('Advanced Ambulance', 'Advanced Ambulance'), ('Intensive Care Unit (ICU) Ambulance', 'Intensive Care Unit (ICU) Ambulance'), ('Specialized Ambulance', 'Specialized Ambulance')], max_length=100)),
                ('additional_comments', models.TextField()),
                ('total_amount', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
